paths:
  file_en: 'sv-en/europarl-v7.sv-en.en'
  file_sv: 'sv-en/europarl-v7.sv-en.sv'
  rebuild_vocabulary: True
  min_freq: 3
  max_vocab_size: 35000
  num_lines: 500000


model_settings:
  num_epochs: 10
  learning_rate: 0.001

batch_size: 64


