paths:
  file_en: 'sv-en/europarl-v7.sv-en.en'
  file_sv: 'sv-en/europarl-v7.sv-en.sv'
  rebuild_vocabulary: False
  min_freq: 3
  max_vocab_size: 35000
  num_lines: 5000


model_settings:
  num_epochs: 20
  learning_rate: 0.0005

batch_size: 128


