# config.yaml
sentence_paths:
  file_en: 'data/english_100k_clean.txt'
  file_sv: 'data/swedish_100k_clean.txt'

logger:
  experiment_name: 'translator'
  project: 'Machine Translation'
  entity: 'team-razbolt'

model_settings:
  num_epochs: 10
  learning_rate: 0.0005
  batch_size: 128
