# config_seq.yaml
sentence_paths:
  file_en: 'data/english_100k_clean.txt'
  file_sv: 'data/swedish_100k_clean.txt'

logger:
  experiment_name: 'translator_seq100k'
  project: 'Machine Translation'
  entity: 'team-razbolt'

model_settings:
  num_epochs: 30
  learning_rate: 0.001
  batch_size: 128