# config.yaml
sentence_paths:
  file_en: 'data/english_100k_clean.txt'
  file_sv: 'data/swedish_100k_clean.txt'

logger:
  experiment_name: 'Transf1_100k'
  project: 'Machine Translation'
  entity: 'team-razbolt'

model_settings:
  num_epochs: 30
  learning_rate: 0.001
  batch_size: 128
  embedding_size: 512
  num_heads: 8
  num_encoder_layers: 3
  num_decoder_layers: 3
  forward_expansion: 4
  dropout: 0.5
  max_sentence_length: 20
